name: "Mon premier worklow"

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "whoami"
      - uses: actions/chec kout@v4
      - run: mkdir "repertoire_1"
      - run: echo "text a afifcher" > repertoire_1/test.txt
      - run: ls -la

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls

