name: "Mon premier worklow"

on: push

jobs:
  job1:
    runs-on: ubuntu:latest
    steps:
      - run: echo "Hello, world"
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: "Afficher le repertoire de travail"
        run: ls
      - run: actions/checkout@v4
      - run: ls
      

